/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutPage {
    }
    interface AppHeader {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface FaIcon {
        /**
          * The icon name. If the name does not start with "fa-", it will be prefixed with it.
         */
        "iconName": string;
        /**
          * Which style of icon set to load from.
         */
        "iconStyle": 'fa' | 'fas';
    }
    interface HomePage {
    }
    interface IpcForm {
    }
    interface NotFoundPage {
    }
}
declare global {
    interface HTMLAboutPageElement extends Components.AboutPage, HTMLStencilElement {
    }
    var HTMLAboutPageElement: {
        prototype: HTMLAboutPageElement;
        new (): HTMLAboutPageElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFaIconElement extends Components.FaIcon, HTMLStencilElement {
    }
    var HTMLFaIconElement: {
        prototype: HTMLFaIconElement;
        new (): HTMLFaIconElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLIpcFormElement extends Components.IpcForm, HTMLStencilElement {
    }
    var HTMLIpcFormElement: {
        prototype: HTMLIpcFormElement;
        new (): HTMLIpcFormElement;
    };
    interface HTMLNotFoundPageElement extends Components.NotFoundPage, HTMLStencilElement {
    }
    var HTMLNotFoundPageElement: {
        prototype: HTMLNotFoundPageElement;
        new (): HTMLNotFoundPageElement;
    };
    interface HTMLElementTagNameMap {
        "about-page": HTMLAboutPageElement;
        "app-header": HTMLAppHeaderElement;
        "app-nav": HTMLAppNavElement;
        "app-root": HTMLAppRootElement;
        "fa-icon": HTMLFaIconElement;
        "home-page": HTMLHomePageElement;
        "ipc-form": HTMLIpcFormElement;
        "not-found-page": HTMLNotFoundPageElement;
    }
}
declare namespace LocalJSX {
    interface AboutPage {
    }
    interface AppHeader {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface FaIcon {
        /**
          * The icon name. If the name does not start with "fa-", it will be prefixed with it.
         */
        "iconName"?: string;
        /**
          * Which style of icon set to load from.
         */
        "iconStyle"?: 'fa' | 'fas';
    }
    interface HomePage {
    }
    interface IpcForm {
    }
    interface NotFoundPage {
    }
    interface IntrinsicElements {
        "about-page": AboutPage;
        "app-header": AppHeader;
        "app-nav": AppNav;
        "app-root": AppRoot;
        "fa-icon": FaIcon;
        "home-page": HomePage;
        "ipc-form": IpcForm;
        "not-found-page": NotFoundPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-page": LocalJSX.AboutPage & JSXBase.HTMLAttributes<HTMLAboutPageElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "fa-icon": LocalJSX.FaIcon & JSXBase.HTMLAttributes<HTMLFaIconElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "ipc-form": LocalJSX.IpcForm & JSXBase.HTMLAttributes<HTMLIpcFormElement>;
            "not-found-page": LocalJSX.NotFoundPage & JSXBase.HTMLAttributes<HTMLNotFoundPageElement>;
        }
    }
}
